version: "3.7"

services:
  db:
    # image: mdillon/postgis:11-alpine
    image: postgres:alpine
    #ports:
    #  - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./web
    volumes:
      - ./web:/web:rw
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      # DATABASE_URL: postgis://postgres@db/postgres
      DATABASE_URL: postgres://postgres@db/postgres
